package Pantalla;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Pablo
 */
public class Pantalla1 extends javax.swing.JFrame {
    DefaultListModel elementosLista = new DefaultListModel();
    Controladora control = new Controladora();
    /**
     * Creates new form Pantalla1
     */
    public Pantalla1() {
        try {
            setIconImage(ImageIO.read(new File(System.getProperty("user.dir") + "/res/kek.png")));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(this);
        botonRadialInventario();
        listaRegistros.setModel(elementosLista);
    }
    
    public void permitirTextos(){
        textoCilindradaMotor.setEditable(true);
        textoCilindrosMotor.setEditable(true);
        textoColorCarroceria.setEditable(true);
        textoDescripcionCarroceria.setEditable(true);
        textoNroCarroceria.setEditable(true);
        textoNroMotor.setEditable(true);
        textoPesoCoche.setEditable(true);
        textoPrecioCarroceria.setEditable(true);
        textoPrecioMotor.setEditable(true);
        TextoMarca.setEditable(true);
        
        botonCrearInventario.setVisible(true);
    }
    
    public void botonRadialInventario(){
        botonCoche.setEnabled(false);
        botonInventario.setEnabled(true);
        botonInventario.setSelected(true);
        botonComponente.setEnabled(false);
        panelInventario.setVisible(true);
        panelCoche.setVisible(false);
        panelComponentes.setVisible(false);
        textoAreaImpresion.setEditable(false);
        botonMostrarAtributo.setEnabled(false);
        botonMostrarInventario.setEnabled(false);
        botonGrabarInventario.setEnabled(false);
        botonCargarCoche.setEnabled(false);
        limpiarTexto();
        elementosLista.removeAllElements();
        permitirTextos();
        
    }
    
    public void botonRadialCoche(){
        botonInventario.setEnabled(false);
        botonMostrarAtributo.setEnabled(true);
        botonMostrarInventario.setEnabled(true);
        botonCoche.setEnabled(true);
        botonCoche.setSelected(true);
        botonCrearInventario.setVisible(false);
        botonGrabarInventario.setEnabled(true);
        TextoMarca.setEditable(false);
        panelCoche.setVisible(true);
        String unItem = "Inventario";
        elementosLista.addElement(unItem);
    }
    
    public void botonRadialComponentes(){
        botonCoche.setEnabled(false);
        botonComponente.setEnabled(true);
        botonComponente.setSelected(true);
        botonCrearCoche.setVisible(false);
        botonAceptarComponentes.setVisible(true);
        botonAceptarComponentes.setEnabled(true);
        
        textoPesoCoche.setEditable(false);
        panelComponentes.setVisible(true);
        
        String unItem = "Coche";
        elementosLista.addElement(unItem);
    }

    void limpiarTexto() {
        TextoMarca.setText("");
        textoAreaImpresion.setText("");
        textoAreaImpresion.setEditable(true);
        textoCilindradaMotor.setText("");
        textoCilindradaMotor.setEditable(true);
        textoCilindrosMotor.setText("");
        textoCilindrosMotor.setEditable(true);
        textoColorCarroceria.setText("");
        textoColorCarroceria.setEditable(true);
        textoDescripcionCarroceria.setText("");
        textoDescripcionCarroceria.setEditable(true);
        textoNroCarroceria.setText("");
        textoNroCarroceria.setEditable(true);
        textoNroMotor.setText("");
        textoNroMotor.setEditable(true);

        textoPesoCoche.setText("");
        textoPesoCoche.setEditable(true);

        textoPrecioCarroceria.setText("");
        textoPrecioCarroceria.setEditable(true);

        textoPrecioMotor.setText("");
        textoPrecioMotor.setEditable(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesEstado = new javax.swing.ButtonGroup();
        panelEstados = new javax.swing.JPanel();
        botonInventario = new javax.swing.JRadioButton();
        botonCoche = new javax.swing.JRadioButton();
        botonComponente = new javax.swing.JRadioButton();
        panelInventario = new javax.swing.JPanel();
        labelMarca = new javax.swing.JLabel();
        TextoMarca = new javax.swing.JTextField();
        botonCrearInventario = new javax.swing.JButton();
        panelCoche = new javax.swing.JPanel();
        labelPeso = new javax.swing.JLabel();
        textoPesoCoche = new javax.swing.JTextField();
        botonCrearCoche = new javax.swing.JButton();
        panelComponentes = new javax.swing.JPanel();
        labelMotor = new javax.swing.JLabel();
        labelNroMotor = new javax.swing.JLabel();
        labelCilindradaMotor = new javax.swing.JLabel();
        labelCilindrosMotor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNroCarroceria = new javax.swing.JLabel();
        labelColorCarroceria = new javax.swing.JLabel();
        labelDescripcionCarroceria = new javax.swing.JLabel();
        labelPrecioCarroceria = new javax.swing.JLabel();
        labelPrecioMotor = new javax.swing.JLabel();
        textoNroMotor = new javax.swing.JTextField();
        textoCilindradaMotor = new javax.swing.JTextField();
        textoCilindrosMotor = new javax.swing.JTextField();
        textoPrecioMotor = new javax.swing.JTextField();
        textoNroCarroceria = new javax.swing.JTextField();
        textoColorCarroceria = new javax.swing.JTextField();
        textoDescripcionCarroceria = new javax.swing.JTextField();
        textoPrecioCarroceria = new javax.swing.JTextField();
        botonAceptarComponentes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRegistros = new javax.swing.JList<>();
        botonMostrarAtributo = new javax.swing.JButton();
        botonMostrarInventario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoAreaImpresion = new javax.swing.JTextArea();
        labelAreaImpresion = new javax.swing.JLabel();
        botonGrabarInventario = new javax.swing.JButton();
        botonCargarCoche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelEstados.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        grupoBotonesEstado.add(botonInventario);
        botonInventario.setText("Inventario");

        grupoBotonesEstado.add(botonCoche);
        botonCoche.setText("Coche");

        grupoBotonesEstado.add(botonComponente);
        botonComponente.setText("Componentes");

        javax.swing.GroupLayout panelEstadosLayout = new javax.swing.GroupLayout(panelEstados);
        panelEstados.setLayout(panelEstadosLayout);
        panelEstadosLayout.setHorizontalGroup(
            panelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonInventario)
                .addGap(46, 46, 46)
                .addComponent(botonCoche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(botonComponente)
                .addGap(17, 17, 17))
        );
        panelEstadosLayout.setVerticalGroup(
            panelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInventario)
                    .addComponent(botonCoche)
                    .addComponent(botonComponente))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        labelMarca.setLabelFor(TextoMarca);
        labelMarca.setText("Marca");

        botonCrearInventario.setText("Crear");
        botonCrearInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCrearInventario))
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearInventario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCoche.setBorder(javax.swing.BorderFactory.createTitledBorder("Coche"));

        labelPeso.setLabelFor(textoPesoCoche);
        labelPeso.setText("Peso");

        botonCrearCoche.setText("Aceptar");
        botonCrearCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCocheLayout = new javax.swing.GroupLayout(panelCoche);
        panelCoche.setLayout(panelCocheLayout);
        panelCocheLayout.setHorizontalGroup(
            panelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCocheLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelPeso)
                .addGap(30, 30, 30)
                .addComponent(textoPesoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCrearCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelCocheLayout.setVerticalGroup(
            panelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCocheLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(textoPesoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCrearCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelComponentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Componentes"));

        labelMotor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelMotor.setText("<html><b><u>Motor</u></b></html>");

        labelNroMotor.setText("Numero");

        labelCilindradaMotor.setText("Cilindrada");

        labelCilindrosMotor.setText("Cilindros");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("<html><b><u>Carroceria</u></b></html>");

        labelNroCarroceria.setText("Numero");

        labelColorCarroceria.setText("Color");

        labelDescripcionCarroceria.setText("Descripcion");

        labelPrecioCarroceria.setText("Precio");

        labelPrecioMotor.setText("Precio");

        botonAceptarComponentes.setText("Aceptar");
        botonAceptarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarComponentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComponentesLayout = new javax.swing.GroupLayout(panelComponentes);
        panelComponentes.setLayout(panelComponentesLayout);
        panelComponentesLayout.setHorizontalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCilindradaMotor)
                            .addComponent(labelNroMotor)
                            .addComponent(labelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecioMotor)
                            .addComponent(labelCilindrosMotor))
                        .addGap(41, 41, 41)))
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoCilindrosMotor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(textoCilindradaMotor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNroMotor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoPrecioMotor))
                        .addGap(152, 152, 152)
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentesLayout.createSequentialGroup()
                                .addComponent(labelPrecioCarroceria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoPrecioCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentesLayout.createSequentialGroup()
                                .addComponent(labelDescripcionCarroceria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoDescripcionCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentesLayout.createSequentialGroup()
                                .addComponent(labelColorCarroceria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoColorCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentesLayout.createSequentialGroup()
                                .addComponent(labelNroCarroceria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoNroCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(111, 111, 111))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(botonAceptarComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelComponentesLayout.setVerticalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNroMotor)
                            .addComponent(textoNroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNroCarroceria)
                            .addComponent(textoNroCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCilindradaMotor)
                            .addComponent(textoCilindradaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelColorCarroceria)
                            .addComponent(textoColorCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescripcionCarroceria)
                            .addComponent(textoDescripcionCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoCilindrosMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCilindrosMotor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioMotor)
                    .addComponent(textoPrecioMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecioCarroceria)
                    .addComponent(textoPrecioCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptarComponentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Registros"));
        listaRegistros.setToolTipText("");
        jScrollPane1.setViewportView(listaRegistros);

        botonMostrarAtributo.setText("Mostrar Atributo");
        botonMostrarAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarAtributoActionPerformed(evt);
            }
        });

        botonMostrarInventario.setText("Listar Inventario");
        botonMostrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarInventarioActionPerformed(evt);
            }
        });

        textoAreaImpresion.setColumns(20);
        textoAreaImpresion.setRows(5);
        jScrollPane2.setViewportView(textoAreaImpresion);

        labelAreaImpresion.setLabelFor(textoAreaImpresion);
        labelAreaImpresion.setText("Area de Impresion");

        botonGrabarInventario.setText("Guardar Inventario");
        botonGrabarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarInventarioActionPerformed(evt);
            }
        });

        botonCargarCoche.setText("Guardar Coche");
        botonCargarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonMostrarAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(botonMostrarInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(labelAreaImpresion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCargarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGrabarInventario))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAreaImpresion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGrabarInventario)
                    .addComponent(botonCargarCoche))
                .addGap(35, 67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMostrarAtributo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonMostrarInventario)))
                .addGap(18, 18, 18)
                .addComponent(panelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearInventarioActionPerformed
        botonRadialCoche();
    }//GEN-LAST:event_botonCrearInventarioActionPerformed

    private void botonCrearCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCocheActionPerformed
        // TODO add your handling code here:
        botonRadialComponentes();
        
    }//GEN-LAST:event_botonCrearCocheActionPerformed

    private void botonAceptarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarComponentesActionPerformed
        botonAceptarComponentes.setVisible(false);
        botonCargarCoche.setEnabled(true);
        textoCilindradaMotor.setEditable(false);
        textoCilindrosMotor.setEditable(false);
        textoColorCarroceria.setEditable(false);
        textoDescripcionCarroceria.setEditable(false);
        textoNroCarroceria.setEditable(false);
        textoNroMotor.setEditable(false);
        textoPesoCoche.setEditable(false);
        textoPrecioCarroceria.setEditable(false);
        textoPrecioMotor.setEditable(false);
        String unItem = "Componente";
        elementosLista.addElement(unItem);
    }//GEN-LAST:event_botonAceptarComponentesActionPerformed

    private void botonMostrarAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarAtributoActionPerformed
        textoAreaImpresion.setText("");
        int index = listaRegistros.getSelectedIndex();
        String linea = " ";
        switch(index){
            case 0:
                linea += "MARCA\n  " + TextoMarca.getText();
                textoAreaImpresion.append(linea);
                break;
            case 1:
                linea += "PESO\n  " + textoPesoCoche.getText()+"kg";
                textoAreaImpresion.append(linea);
                break;
            case 2: 
                linea += "MOTOR\n  Cilindrada  " + textoCilindradaMotor.getText()+"\n  Cilindros  " + textoCilindrosMotor.getText()
                        + "\n  Numero  " + textoNroMotor.getText()+"\n  Precio  " + textoPrecioMotor.getText() +
                         "\nCARROCERÍA\n  Numero  " + textoNroCarroceria.getText() + "\n  Color  " + textoColorCarroceria.getText() +
                        "\n  Descripcion  " + textoDescripcionCarroceria.getText() + "\n  Precio  " + textoPrecioCarroceria.getText();
                textoAreaImpresion.append(linea);
                break;
            default:
                textoAreaImpresion.append("NO SE HA SELECCIONADO NINGUN ELEMENTO, POR FAVOR SELECCIONE UNO");
        }
    }//GEN-LAST:event_botonMostrarAtributoActionPerformed

    private void botonCargarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarCocheActionPerformed
        // TODO add your handling code here:
        
        String marca = (String)TextoMarca.getText(); 
        int peso = Integer.parseInt(textoPesoCoche.getText());
        int cantidadCilindros = Integer.parseInt(textoCilindrosMotor.getText());
        int cilindrada = Integer.parseInt(textoCilindradaMotor.getText());
        Integer documentoMotor = Integer.parseInt(textoNroMotor.getText());
        float precioMotor = Float.parseFloat(textoPrecioMotor.getText());
        String color = textoColorCarroceria.getText(); 
        String descripcion = textoDescripcionCarroceria.getText();
        Integer documentoCarroceria = Integer.parseInt(textoNroCarroceria.getText());
        float precioCarroceria =  Float.parseFloat(textoPrecioCarroceria.getText());
        
        control.grabarCoche(peso, cantidadCilindros, cilindrada, documentoMotor, precioMotor, color, descripcion, 
                documentoCarroceria, precioCarroceria);
        
        elementosLista.removeAllElements();
        botonCargarCoche.setEnabled(false);
        botonInventario.setEnabled(false);
        botonComponente.setEnabled(false);
        botonCoche.setEnabled(true);
        botonCoche.setSelected(true);
        botonCrearInventario.setVisible(false);
        botonCrearCoche.setVisible(true);
        botonCrearCoche.setEnabled(true);
        botonMostrarAtributo.setEnabled(true);
        botonMostrarInventario.setEnabled(true);
        botonGrabarInventario.setEnabled(true);
        TextoMarca.setEditable(false);
        panelCoche.setVisible(true);
        panelComponentes.setVisible(false);
        String unItem = "Inventario";
        elementosLista.addElement(unItem);
    }//GEN-LAST:event_botonCargarCocheActionPerformed

    private void botonMostrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarInventarioActionPerformed
        String marca = TextoMarca.getText();
        control.listarInventario(marca);
    }//GEN-LAST:event_botonMostrarInventarioActionPerformed

    private void botonGrabarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarInventarioActionPerformed
        
        String marca = TextoMarca.getText();
        try {
            control.grabarInventario(marca);
        } 
        catch (Exception ex) {
            ex.printStackTrace();
        }
        limpiarTexto();
        elementosLista.removeAllElements();
        botonRadialInventario();
    }//GEN-LAST:event_botonGrabarInventarioActionPerformed

    public static void main(String[] args) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoMarca;
    private javax.swing.JButton botonAceptarComponentes;
    private javax.swing.JButton botonCargarCoche;
    private javax.swing.JRadioButton botonCoche;
    private javax.swing.JRadioButton botonComponente;
    private javax.swing.JButton botonCrearCoche;
    private javax.swing.JButton botonCrearInventario;
    private javax.swing.JButton botonGrabarInventario;
    private javax.swing.JRadioButton botonInventario;
    private javax.swing.JButton botonMostrarAtributo;
    private javax.swing.JButton botonMostrarInventario;
    private javax.swing.ButtonGroup grupoBotonesEstado;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAreaImpresion;
    private javax.swing.JLabel labelCilindradaMotor;
    private javax.swing.JLabel labelCilindrosMotor;
    private javax.swing.JLabel labelColorCarroceria;
    private javax.swing.JLabel labelDescripcionCarroceria;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelMotor;
    private javax.swing.JLabel labelNroCarroceria;
    private javax.swing.JLabel labelNroMotor;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPrecioCarroceria;
    private javax.swing.JLabel labelPrecioMotor;
    private javax.swing.JList<String> listaRegistros;
    private javax.swing.JPanel panelCoche;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelEstados;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JTextArea textoAreaImpresion;
    private javax.swing.JTextField textoCilindradaMotor;
    private javax.swing.JTextField textoCilindrosMotor;
    private javax.swing.JTextField textoColorCarroceria;
    private javax.swing.JTextField textoDescripcionCarroceria;
    private javax.swing.JTextField textoNroCarroceria;
    private javax.swing.JTextField textoNroMotor;
    private javax.swing.JTextField textoPesoCoche;
    private javax.swing.JTextField textoPrecioCarroceria;
    private javax.swing.JTextField textoPrecioMotor;
    // End of variables declaration//GEN-END:variables
}
